# Generated by Django 6.0.2 on 2026-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_is_2fa_enabled_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='sent_via_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='sent_via_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('RESET', 'Reset')], max_length=20),
        ),
    ]
